# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67022d9bbad7f561a496fd1bf48a52eddeea9cbef289ba5df3594fb75046337b0bb17b841366bffc3ae2bbf118506a916b4e2328354cbddbb2333a6cadd35e82

test:
  secret_key_base: 04c6a91f9d46c2044a8d17ad8dfd85e31b5b9bfeb4304b868bb455c0233bd3979e5f24b25913cffdf20c4b35e664dec60745a19edb082cbb08c9e566c0ed8a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
